/* MASTERED_ADDON_V1 */
let masteredLevel="ALL";
function LmasteredEntries(){return LallLearningCards().filter(c=>Lmastered(Lstate(c))).sort((a,b)=>{const lv=LcmpLevel(a.level,b.level);if(lv)return lv;const ch=LcmpLevel(a.chapter,b.chapter);if(ch)return ch;return a.de.localeCompare(b.de,"de")})}
function LmasteredVisible(){const all=LmasteredEntries();return masteredLevel==="ALL"?all:all.filter(c=>c.level===masteredLevel)}
function LupdateMasteredBadge(){const n=LmasteredEntries().length;if(L$("learnMasteredCount"))L$("learnMasteredCount").textContent=n;if(typeof LupdateWrongBadge==="function")LupdateWrongBadge()}
function LmasteredStyles(){const st=document.createElement("style");st.textContent=`.masterOverlay{position:fixed;inset:0;z-index:9998;background:rgba(18,25,38,.58);display:flex;align-items:flex-end;justify-content:center}.masterOverlay.hidden{display:none}.masterSheet{background:#fff;width:min(760px,100%);max-height:92vh;border-radius:20px 20px 0 0;padding:18px;overflow:auto;box-shadow:0 -16px 50px rgba(0,0,0,.18)}.masterHead{display:flex;align-items:center;justify-content:space-between;gap:12px;position:sticky;top:-18px;background:#fff;padding:16px 0 10px;z-index:2}.masterHead h2{margin:0;font-size:24px}.masterTools{display:flex;gap:8px;align-items:end;flex-wrap:wrap;margin:8px 0 12px}.masterTools label{min-width:150px}.masterList{display:grid;gap:10px}.masterItem{border:1px solid var(--line);border-radius:14px;padding:13px;background:#fff}.masterTop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.masterWord{font-size:21px;font-weight:800}.masterMeaning{margin-top:3px}.masterMeta{font-size:12px;color:var(--muted);margin-top:5px}.masterEmpty{text-align:center;padding:45px 10px;color:var(--muted)}.masterRemove{white-space:nowrap}.masterClickable{cursor:pointer}@media(min-width:700px){.masterOverlay{align-items:center;padding:18px}.masterSheet{border-radius:20px;max-height:88vh}}`;document.head.appendChild(st)}
function LbuildMasteredUI(){LmasteredStyles();const ov=document.createElement("div");ov.id="masteredOverlay";ov.className="masterOverlay hidden";ov.innerHTML=`<div class="masterSheet"><div class="masterHead"><h2>已掌握单词</h2><button class="secondary" id="masteredClose">关闭</button></div><div id="masteredContent"></div></div>`;document.body.appendChild(ov);L$("masteredClose").onclick=LcloseMastered;ov.addEventListener("click",e=>{if(e.target===ov)LcloseMastered()})}
function LopenMastered(){LrenderMasteredList();L$("masteredOverlay").classList.remove("hidden")}
function LcloseMastered(){L$("masteredOverlay").classList.add("hidden")}
function LrenderMasteredList(){const all=LmasteredEntries(),entries=LmasteredVisible(),box=L$("masteredContent");box.innerHTML=`<div class="coverage"><b>已掌握 ${all.length} 个。</b> 已掌握词退出新词、日常复习、拼写错题复习和单词检测，但会在间隔到期后回到今日任务里<b>抽查一次</b>：答对就推得更远（14 天 → 30 天 → 90 天），答错就退回“学习中”。也可以手动“移出已掌握”。</div><div class="masterTools"><label>查看级别<select id="masteredLevel">${LlevelChoices()}</select></label></div>${entries.length?`<div class="masterList">${entries.map(c=>{const zh=LhasZh(c)?Lmeaning(c):"",en=Lenglish(c);return `<div class="masterItem"><div class="masterTop"><div><div class="masterWord">${Lesc(c.de)}</div><div class="masterMeaning">${zh?`${Lesc(zh)} <span class="masterMeta">· ${Lesc(en)}</span>`:Lesc(en)}</div><div class="masterMeta">${Lesc(c.level)} · Kapitel ${Lesc(String(c.chapter))}</div></div><button class="secondary masterRemove" data-id="${Lesc(c.id)}">移出已掌握</button></div></div>`}).join("")}</div>`:`<div class="masterEmpty"><h3>${all.length?"这个级别还没有已掌握单词":"目前还没有已掌握单词"}</h3><p>完成足够的记忆轮次，或在认识阶段选择“这个我已经会”，都会进入这里。</p></div>`}`;L$("masteredLevel").value=masteredLevel;L$("masteredLevel").onchange=e=>{masteredLevel=e.target.value;LrenderMasteredList()};document.querySelectorAll(".masterRemove").forEach(b=>b.onclick=()=>LremoveMastered(b.dataset.id))}
function LremoveMastered(id){const c=CARDS.find(x=>x.id===id);if(!c)return;const s=Lstate(c);if(!confirm(`把“${c.de}”移出已掌握吗？\n\n它会回到“学习中 / 待复习”，之后可以再次出现。`))return;s.known=false;s.cycles=0;s.strength=Math.min(2,s.strength||0);s.spellingPass=false;s.introduced=true;s.due=Date.now();s.last=Date.now();Lsave(c,s);if(typeof bank==="function")bank();LrenderMasteredList();LupdateMasteredBadge()}
function LinitMasteredUI(){if(typeof window.filtered==="function"&&!window.__masteredFilteredV1){const baseFiltered=window.filtered;window.filtered=function(){return baseFiltered().filter(c=>!Lmastered(Lstate(c)))};window.__masteredFilteredV1=true}const wrong=L$("learnWrongBtn"),review=L$("learnReviewBtn");if(!L$("learnMasteredBtn")){const b=document.createElement("button");b.id="learnMasteredBtn";b.className="secondary";b.innerHTML='已掌握 <span id="learnMasteredCount">0</span>';(wrong||review).after(b);b.onclick=LopenMastered}const homeStat=L$("homeMastered")?.closest(".stat"),learnStat=L$("lMastered")?.closest(".stat");for(const el of [homeStat,learnStat])if(el){el.classList.add("masterClickable");el.title="查看已掌握单词";el.onclick=LopenMastered}LbuildMasteredUI();const baseSave=Lsave;Lsave=function(c,s){baseSave(c,s);LupdateMasteredBadge()};const baseHomeStats=LhomeStats;LhomeStats=function(){baseHomeStats();LupdateMasteredBadge()};LupdateMasteredBadge()}
