/* WRONGBOOK_ADDON_V1 */
const WRONG_KEY=DWStore.KEYS.WRONG;
let wrongBook=DWStore.read(WRONG_KEY,{});
DWStore.onMigrated(()=>{wrongBook=DWStore.read(WRONG_KEY,{})});
let wrongPractice=[],wrongPos=0,wrongScore=0,wrongAnswered=false;
function LpruneWrongBook(){if(typeof Lmastered!=="function"||typeof CARDS==="undefined"||!CARDS.length)return;const byId=new Map(CARDS.map(c=>[c.id,c]));for(const id of Object.keys(wrongBook)){const c=byId.get(id);if(!c||Lmastered(Lstate(c)))delete wrongBook[id]}}
function LsaveWrongBook(){LpruneWrongBook();DWStore.queue(WRONG_KEY,()=>wrongBook);LupdateWrongBadge()}
function LwrongEntries(){return Object.values(wrongBook).filter(e=>{const c=CARDS.find(x=>x.id===e.id);return !c||!Lmastered(Lstate(c))}).sort((a,b)=>(b.lastAt||0)-(a.lastAt||0))}
function LwrongSpellResult(c,input,show,ok){if(show||!input)return;const now=Date.now(),old=wrongBook[c.id]||{};if(ok){if(!old.id)return;old.correctStreak=(old.correctStreak||0)+1;old.lastCorrectAt=now;wrongBook[c.id]=old;LsaveWrongBook();return}wrongBook[c.id]={id:c.id,level:c.level,chapter:String(c.chapter),de:c.de,zh:LhasZh(c)?Lmeaning(c):"",en:Lenglish(c),wrongCount:(old.wrongCount||0)+1,firstAt:old.firstAt||now,lastAt:now,lastInput:input,correctStreak:0,lastCorrectAt:old.lastCorrectAt||0};LsaveWrongBook()}
function LupdateWrongBadge(){const n=LwrongEntries().length;if(L$("learnWrongCount"))L$("learnWrongCount").textContent=n;if(L$("homeSpellingWrong"))L$("homeSpellingWrong").textContent=n}
const LflatUml=s=>String(s||"").toLowerCase().replace(/ä/g,"a").replace(/ö/g,"o").replace(/ü/g,"u").replace(/ß/g,"ss");
function Ldistance(a,b){const m=a.length,n=b.length;if(!m||!n)return Math.max(m,n);let prev=Array.from({length:n+1},(_,j)=>j);for(let i=1;i<=m;i++){const cur=[i];for(let j=1;j<=n;j++)cur[j]=Math.min(prev[j]+1,cur[j-1]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}return prev[n]}
function LwrongCause(e){const typed=(e.lastInput||"").trim();if(!typed)return null;const want=e.de||"";
 const tn=Lnorm(typed),wn=Lnorm(want);
 if(tn===wn)return null;
 const tb=LwithoutArticle(tn),wb=LwithoutArticle(wn);
 if(tb===wb)return "article";
 if(LflatUml(tb)===LflatUml(wb))return /ß/.test(want)||/ss/.test(typed)?"eszett":"umlaut";
 if(Ldistance(tb,wb)<=2)return "typo";
 return "other"}
const LCAUSE_LABEL={umlaut:"变音漏写或写错（ä ö ü）",eszett:"ß / ss 混淆",article:"冠词错（der/die/das）",typo:"拼写接近，差 1–2 个字母",other:"完全不同的词"};
function LwrongCauseSummary(entries){const tally={};let n=0;for(const e of entries){const c=LwrongCause(e);if(!c)continue;tally[c]=(tally[c]||0)+1;n++}
 if(!n)return "";const rows=Object.entries(tally).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="causeRow"><span>${Lesc(LCAUSE_LABEL[k]||k)}</span><span><b>${v}</b> 次 · ${Math.round(v/n*100)}%</span></div>`).join("");
 return `<div class="causeBox"><b>错因分析（${n} 个有记录的错误）</b>${rows}</div>`}
// A retry has to be scored exactly the way the original miss was scored. This
// used to be a second copy of the rule, which is how the wrong-book kept marking
// reflexive verbs wrong after the learning mode had stopped.
function LstoredSpellAccepted(e,input){return LspellAccepted(typeof e==="string"?{de:e}:e,input)}
function LwrongStyles(){const st=document.createElement("style");st.textContent=`.wrongOverlay{position:fixed;inset:0;z-index:9999;background:rgba(18,25,38,.58);display:flex;align-items:flex-end;justify-content:center}.wrongOverlay.hidden{display:none}.wrongSheet{background:#fff;width:min(760px,100%);max-height:92vh;border-radius:22px 22px 0 0;padding:18px;overflow:auto;box-shadow:0 -16px 50px rgba(0,0,0,.18)}.wrongHead{display:flex;align-items:center;justify-content:space-between;gap:12px;position:sticky;top:-18px;background:#fff;padding:16px 0 10px;z-index:2}.wrongHead h2{margin:0;font-size:24px}.wrongList{display:grid;gap:10px;margin-top:12px}.wrongItem{border:1px solid var(--line);border-radius:14px;padding:13px;background:#fff}.wrongTop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.wrongWord{font-size:21px;font-weight:800}.wrongMeta{font-size:12px;color:var(--muted);margin-top:4px}.wrongInput{margin-top:8px;padding:8px 10px;border-radius:9px;background:#fff2f2;color:#9d2f2f}.wrongActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.wrongActions button{padding:9px 11px}.wrongEmpty{text-align:center;padding:45px 10px;color:var(--muted)}.wrongPracticeWord{font-size:32px;font-weight:800;margin:12px 0}.wrongPracticeMeaning{font-size:24px;font-weight:750;margin:20px 0 4px}.wrongPracticeBox{margin-top:18px}.wrongPracticeBox input{width:100%;margin-bottom:10px}.wrongMini{font-size:12px;color:var(--muted)}.causeBox{border:1px solid var(--line);border-radius:14px;padding:13px;margin-bottom:12px;background:#fafbff;display:grid;gap:7px}.causeRow{display:flex;justify-content:space-between;gap:10px;font-size:13px;color:var(--muted)}.causeRow b{color:var(--ink)}.causeTag{display:inline-block;margin-top:4px;font-size:11px;background:#fff;border:1px solid #e3c9c9;border-radius:999px;padding:2px 8px;color:#9d2f2f}@media(min-width:700px){.wrongOverlay{align-items:center;padding:18px}.wrongSheet{border-radius:22px;max-height:88vh}}`;document.head.appendChild(st)}
function LbuildWrongBookUI(){LwrongStyles();const ov=document.createElement("div");ov.id="wrongOverlay";ov.className="wrongOverlay hidden";ov.innerHTML=`<div class="wrongSheet"><div class="wrongHead"><h2>📕 拼写错题本</h2><button class="secondary" id="wrongClose">关闭</button></div><div id="wrongContent"></div></div>`;document.body.appendChild(ov);L$("wrongClose").onclick=LcloseWrongBook;ov.addEventListener("click",e=>{if(e.target===ov)LcloseWrongBook()})}
function LopenWrongBook(){LrenderWrongList();L$("wrongOverlay").classList.remove("hidden")}
function LcloseWrongBook(){L$("wrongOverlay").classList.add("hidden")}
function LrenderWrongList(){const entries=LwrongEntries(),box=L$("wrongContent");if(!entries.length){box.innerHTML=`<div class="wrongEmpty"><div style="font-size:42px">✨</div><h3>目前没有需要复习的拼写错题</h3><p>只有在“主动拼写”阶段真正输入错误的单词才会收录；已掌握的词会自动退出错题复习。</p></div>`;return}box.innerHTML=`${LwrongCauseSummary(entries)}<div class="coverage"><b>当前有 ${entries.length} 个待复习拼写错词。</b> 按最近出错时间排序；已掌握的词不会再进入错题复习。</div><div class="wrongActions"><button class="primary" id="wrongPracticeBtn">开始复习错题</button><button class="secondary" id="wrongClearBtn">清空错题本</button></div><div class="wrongList">${entries.map(e=>`<div class="wrongItem"><div class="wrongTop"><div><div class="wrongWord">${Lesc(e.de)}</div><div>${e.zh?`${Lesc(e.zh)} <span class="wrongMeta">· ${Lesc(e.en)}</span>`:Lesc(e.en)}</div><div class="wrongMeta">${Lesc(e.level)} · Kapitel ${Lesc(e.chapter)} · 拼错 ${e.wrongCount||1} 次${e.correctStreak?` · 最近连续答对 ${e.correctStreak} 次`:""}</div></div><button class="secondary wrongRemove" data-id="${Lesc(e.id)}">移出</button></div>${e.lastInput?`<div class="wrongInput">上次写成：${Lesc(e.lastInput)}${(()=>{const c=LwrongCause(e);return c?` <span class="causeTag">${Lesc(LCAUSE_LABEL[c])}</span>`:""})()}</div>`:""}</div>`).join("")}</div>`;L$("wrongPracticeBtn").onclick=LstartWrongPractice;L$("wrongClearBtn").onclick=()=>{if(confirm("确定清空整个拼写错题本吗？学习进度不会被清空。")){wrongBook={};LsaveWrongBook();LrenderWrongList()}};document.querySelectorAll(".wrongRemove").forEach(b=>b.onclick=()=>{delete wrongBook[b.dataset.id];LsaveWrongBook();LrenderWrongList()})}
function LstartWrongPractice(){wrongPractice=Lshuffle(LwrongEntries());if(!wrongPractice.length)return;wrongPos=0;wrongScore=0;wrongAnswered=false;LrenderWrongPractice()}
function LrenderWrongPractice(){const box=L$("wrongContent");if(wrongPos>=wrongPractice.length){const total=wrongPractice.length,pct=total?Math.round(wrongScore/total*100):100;box.innerHTML=`<div class="sessionDone"><div class="big">📕</div><h2>错题复习完成</h2><p class="sub">${wrongScore} / ${total} 正确，正确率 ${pct}%。错题不会自动删除，你确认已经稳了再手动移出即可。</p><div class="wrongActions"><button class="primary" id="wrongAgain">再练一遍</button><button class="secondary" id="wrongBackList">返回错题列表</button></div></div>`;L$("wrongAgain").onclick=LstartWrongPractice;L$("wrongBackList").onclick=LrenderWrongList;return}wrongAnswered=false;const e=wrongPractice[wrongPos];box.innerHTML=`<div class="wrongMini">错题 ${wrongPos+1} / ${wrongPractice.length} · ${Lesc(e.level)} Kapitel ${Lesc(e.chapter)}</div><div class="wrongPracticeMeaning">${Lesc(e.zh||e.en)}</div>${e.zh?`<div class="learnEn">${Lesc(e.en)}</div>`:""}<div class="wrongPracticeBox"><input id="wrongAnswer" type="text" autocomplete="off" autocapitalize="none" spellcheck="false" enterkeyhint="done" placeholder="重新拼写德语…">${LcharBar("wrongAnswer")}<div class="wrongActions"><button class="primary" id="wrongCheck">检查</button><button class="secondary" id="wrongShow">看答案</button></div></div><div id="wrongFeedback"></div>`;const input=L$("wrongAnswer"),check=show=>LcheckWrongPractice(e,show);L$("wrongCheck").onclick=()=>check(false);L$("wrongShow").onclick=()=>check(true);input.addEventListener("keydown",ev=>{if(ev.key==="Enter"){ev.preventDefault();check(false)}});setTimeout(()=>input.focus(),60)}
function LcheckWrongPractice(e,show){if(wrongAnswered)return;const input=L$("wrongAnswer"),v=input.value.trim();if(!show&&!v)return;wrongAnswered=true;const ok=!show&&LstoredSpellAccepted(e,v);if(ok){wrongScore++;e.correctStreak=(e.correctStreak||0)+1;e.lastCorrectAt=Date.now()}else if(!show){e.wrongCount=(e.wrongCount||0)+1;e.lastInput=v;e.lastAt=Date.now();e.correctStreak=0}wrongBook[e.id]=e;LsaveWrongBook();input.disabled=true;L$("wrongCheck").disabled=true;L$("wrongShow").disabled=true;const fb=L$("wrongFeedback");fb.className="feedback show "+(ok?"ok":"no");fb.innerHTML=`<b>${ok?"✓ 拼对了":"✗ 正确拼写"}</b><div class="answerRow"><div class="wrongPracticeWord">${Lesc(e.de)}</div>${LspeakBtn(e.de)}</div>${!ok&&!show?`<div class="wrongInput">你写的是：${Lesc(v)}</div>`:""}<div class="wrongActions"><button class="primary" id="wrongNext">下一题</button></div>`;L$("wrongNext").onclick=()=>{wrongPos++;LrenderWrongPractice()}}
function LinitWrongBookUI(){const review=L$("learnReviewBtn");if(review&&!L$("learnWrongBtn")){const b=document.createElement("button");b.id="learnWrongBtn";b.className="secondary";b.innerHTML='📕 拼写错题本 <span id="learnWrongCount">0</span>';review.after(b);b.onclick=LopenWrongBook}const stats=document.querySelector("#homeView .stats");if(stats&&!L$("homeSpellingWrong")){const d=document.createElement("div");d.className="stat";d.innerHTML='<b id="homeSpellingWrong">0</b><span>拼写错题</span>';stats.appendChild(d)}const cov=document.querySelector("#learnView .coverage");if(cov)cov.insertAdjacentHTML("beforeend"," 主动拼写阶段真正写错的词会自动进入拼写错题本。");LbuildWrongBookUI();LupdateWrongBadge()}
